### ISSUE TITLE
Remove ThreadLocal, redesign it or provide very strong motivation for it.

### ISSUE THREAD

**Issue by bwsw** [bwsw/cs-vault-server#57]
https://github.com/bwsw/cs-vault-server/blob/7110f5d1ccef01edcd729635d40f54d28527cd50/src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackTaskCreator.scala#L48

Why it's "var" not "val" btw. Why the name is "threadLocalClientList" is it means something, do you think "clientList" is a bad name for it?

**Comment by bwsw** [comment]
@placccebo @Krisilda 
Looks like all the class 
https://github.com/bwsw/cs-vault-server/blob/develop/src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackTaskCreator.scala#L48

is copypasted from JAVA to SCALA. Don't do that. Use external dependency or reimplement in a proper way.

**Comment by placccebo** [comment]
@bwsw 
which one? CloudStackTaskCreator? Please, explain me, what you mean by the proper way.

**Comment by bwsw** [comment]
@placccebo Yes, I don't like the implementation at all. It looks like a bad design to use thread-contextual variable rather than just create client object when you need it and use it, destroying after.

**Comment by MedvedevBW** [comment]
@bwsw  I use list with clients (note: client not connected to server while creating) for each thread ( local in thread context and global in class context) , because next client at the list will be used for all next requests in thread after unsuccessfull request to server with current client.
If use local client list, and for example the first client will have url to unavailable server, we will have an "unavailable server" exception for each first request: userIds.foreach(x => setTagToResource(taglist)) fail will be for each first request for each user.
If use global var clientList for all thread, we will have some problem with changed it. If two thread change the list with clients at the same time, we miss one client for next try to connection.
