### ISSUE TITLE
Make action plan to change cs-vault-server project according to changes in cs-entities and cs-kafka-reader

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-vault-server#83]
Which components should be replaced by components from others projects. 
Try to divide into tasks.

**Comment by MedvedevBW** [comment]
1. Change UML diagrams with considering the next points (each system/library should be framed with a package).
2. Use kafka-reader library:
  a. ConsumerManager should be replaced by EventManager which works with kafka-reader library as described in the sequence diagram (use the default implementations of Consumer, CheckpointInfoProcessor and MessageQueue) https://www.draw.io/?state=%7B%22ids%22:%5B%221GnLMP61DmxYcbO4WilHoIw7ZgHl8zxGh%22%5D,%22action%22:%22open%22,%22userId%22:%22102063714460262409036%22%7D#G1GnLMP61DmxYcbO4WilHoIw7ZgHl8zxGh
  b. Implement CloudStackEventHandler according to EventHandler
NB: make "groupId" setting configurable
3. Use cs-entities library:
  a. Use the implementation of GenericDao for Account, Tag, and VirtualMachine entities instead of CloudStackTaskCreator in CloudStackService
  b. Replace setResourceTags with the following methods: setAccountTags and setVmTags

**Comment by MedvedevBW** [comment]
https://docs.google.com/document/d/1w03aeULXEf0ab0B7l1aqjyRimHbIsk4detlJEf4r5zo/edit
